sudo: required

services:
    - docker

before_install:
    - docker build -t test/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true test/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "frontend"
    env: "Frontend-env"
    bucket_name: "elasticbeanstalk-us-east-2-112543432448"
    bucket_path: "frontend"
    on:
        branch: master # means every time push code to master, time to deploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: "$AWS_SECRET_KEY"
