sudo: required
services:
    - docker

before_install:
    - docker build -t shirelyli9444/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true shirelyli9444/docker-react npm run test -- --coverage
